export const LOGINREQ= "LOGINREQ"
 export const LOGINSUCC = "LOGINSUCC"
 export const LOGINERR = "LOGINSUCC"
 export const SIGNINREQ= "LOGINREQ"
 export const SIGNINSUCC = "LOGINSUCC"
 export const SIGNINERR = "LOGINSUCC"